# Generated by Django 5.2.2 on 2025-06-06 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='demand_forecast',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='optimized_price',
            field=models.FloatField(default=0.0),
        ),
    ]
